; Extensions
extension_dir = "ext"

extension=zip
extension=curl
extension=openssl

; opcjonalnie:
extension=mbstring
extension=gd
;extension=mysqli
;extension=pdo_mysql
;extension=pdo_sqlite
;extension=sqlite3

; OPcache
opcache.enable=0
opcache.enable_cli=0

; Date
date.timezone=Europe/Warsaw

; Errors
error_reporting=E_ALL
display_errors=Off
display_startup_errors=Off
log_errors=On

; General
short_open_tag=On
ignore_user_abort=Off
implicit_flush=Off
output_buffering=0
default_charset="UTF-8"

; Execution time
max_execution_time=30

; Memory
memory_limit=128M

; File uploads
max_file_uploads=20
upload_max_filesize=2048M
post_max_size=2048M

; SMTP
SMTP=127.0.0.1
smtp_port=25